services:
  web:
    build:
      context: ./app
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ../nginx-static/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
      - pgadmin-servers:/pgadmin4/servers.json

volumes:
  pgadmin:
  postgres:
  pgadmin-servers:
